tn-asat/TeamProject

src/main/webapp/WEB-INF/views/product/product_view.jsp

프로젝트 뷰 jsp 추가

---

src/main/webapp/WEB-INF/views/include/floor.jsp
src/main/webapp/WEB-INF/views/include/floor2.jsp
src/main/webapp/WEB-INF/views/product/product_write3.jsp
src/main/webapp/resources/css/mystyle.css

Product_write (jQuery)

---

src/main.java/com/hanulso/controller/AdminController.java
src/main/webapp/WEB-INF/views/admin/manage/admin_cor_list.jsp
src/main/webapp/WEB-INF/views/admin/manage/admin_user_list.jsp
src/main/webapp/WEB-INF/views/include/header.jsp

관리자 회원관리 페이지

---

src/main.java/com/hanulso/controller/AdminController.java
src/main.java/com/hanulso/controller/UserController.java
src/main.java/com/hanulso/domain/UserVO.java
src/main.java/com/hanulso/mapper/UserMapper.java
src/main.java/com/hanulso/mapper/UserMapper.xml
src/main.java/com/hanulso/security/CustomLoginSuccessHandler.java
src/main.java/com/hanulso/security/CustomUserDetails.java
src/main.java/com/hanulso/security/CustomUserDetailsService.java
src/main.java/com/hanulso/service/UserService.java
src/main.java/com/hanulso/service/UserServiceImpl.java
src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
src/main/webapp/WEB-INF/views/admin/manage/admin_user_list.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/user/user_register_admin.jsp

Login Base

---

src/main/webapp/WEB-INF/views/map/map_view.jsp
src/main/webapp/resources/css/mystyle.css

Map_view modal 창 수정

---

src/main.java/com/hanulso/controller/NoticeController.java
src/main.java/com/hanulso/domain/Criteria.java
src/main.java/com/hanulso/domain/PageVO.java
src/main.java/com/hanulso/mapper/NoticeMapper.java
src/main.java/com/hanulso/mapper/NoticeMapper.xml
src/main.java/com/hanulso/service/NoticeService.java
src/main.java/com/hanulso/service/NoticeServiceImpl.java
src/main/webapp/WEB-INF/views/notice/notice_list.jsp

공지사항 검색+페이지

---

src/main/webapp/WEB-INF/views/index.jsp

인덱스 페이지의 FAQ

---

target/classes/com/hanulso/mapper/FavoriteMapper.xml

favorite Mapper 추가

---

src/main.java/com/hanulso/controller/NoticeController.java
src/main.java/com/hanulso/mapper/AlertMapper.xml
src/main.java/com/hanulso/mapper/NoticeMapper.java
src/main.java/com/hanulso/mapper/NoticeMapper.xml

잘돌아가게 하기위한 약간의 수정

---

.classpath
.settings/org.eclipse.wst.common.component
src/main.java/com/hanulso/controller/CorController.java
src/main.java/com/hanulso/controller/ProductController.java
src/main.java/com/hanulso/controller/UserController.java
src/main/webapp/WEB-INF/views/coroperation/cor_view.jsp
src/main/webapp/WEB-INF/views/favorite/looked_room.jsp
src/main/webapp/WEB-INF/views/product/product_view.jsp
src/main/webapp/WEB-INF/views/user/user_register_admin.jsp

중개사 뷰 > 매물 뷰 수정

---

.settings/org.eclipse.wst.common.component
src/main.java/com/hanulso/controller/KakaoController.java
src/main.java/com/hanulso/controller/UserController.java
src/main.java/com/hanulso/domain/UserVO.java
src/main.java/com/hanulso/mapper/UserMapper.java
src/main.java/com/hanulso/mapper/UserMapper.xml
src/main.java/com/hanulso/service/UserService.java
src/main.java/com/hanulso/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/user/user_login.jsp

카카오 로그인 / 로그아웃

---

src/main.java/com/hanulso/controller/HomeController.java
src/main.java/com/hanulso/controller/ProductController.java
src/main.java/com/hanulso/mapper/IndexMapper.java
src/main.java/com/hanulso/mapper/IndexMapper.xml
src/main.java/com/hanulso/mapper/ProductMapper.java
src/main.java/com/hanulso/mapper/ProductMapper.xml
src/main.java/com/hanulso/mapper/TipMapper.xml
src/main.java/com/hanulso/service/IndexService.java
src/main.java/com/hanulso/service/IndexServiceImpl.java
src/main.java/com/hanulso/service/ProductService.java
src/main.java/com/hanulso/service/ProductServiceImpl.java
src/main/webapp/WEB-INF/views/admin/manage/admin_cor_list.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/notice/notice_list.jsp
src/main/webapp/WEB-INF/views/tip/tip_list.jsp
src/main/webapp/WEB-INF/views/tip/tip_modify.jsp
src/main/webapp/WEB-INF/views/tip/tip_write.jsp

메인페이지 수정 및 뷰카운트(쿠키X)

---

src/main.java/com/hanulso/controller/CorController.java
src/main.java/com/hanulso/controller/UserController.java
src/main.java/com/hanulso/mapper/ProductMapper.java
src/main.java/com/hanulso/mapper/ProductMapper.xml
src/main.java/com/hanulso/service/ProductService.java
src/main.java/com/hanulso/service/ProductServiceImpl.java
src/main/webapp/WEB-INF/views/coroperation/cor_view.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/map/map_view.jsp
src/main/webapp/WEB-INF/views/user/user_login.jsp
src/main/webapp/WEB-INF/views/user/user_modify_kakao.jsp
src/main/webapp/WEB-INF/views/user/user_password_check.jsp
src/main/webapp/resources/css/mystyle.css

카카오 회원 정보 수정 / 중개사 뷰 수정

---

src/main.java/com/hanulso/controller/HomeController.java
src/main.java/com/hanulso/mapper/IndexMapper.java
src/main.java/com/hanulso/mapper/IndexMapper.xml
src/main.java/com/hanulso/service/IndexService.java
src/main.java/com/hanulso/service/IndexServiceImpl.java
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/map/map_modal_view.jsp
src/main/webapp/WEB-INF/views/product/product_view.jsp

인기매물순위(메인페이지)

---

src/main.java/com/hanulso/controller/UserController.java
src/main.java/com/hanulso/mapper/UserMapper.java
src/main.java/com/hanulso/mapper/UserMapper.xml
src/main.java/com/hanulso/service/UserService.java
src/main.java/com/hanulso/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/user/user_modify_cor.jsp

중개사 회원 정보 수정

---

src/main.java/com/hanulso/controller/AlertController.java
src/main.java/com/hanulso/controller/FavoriteCotroller.java
src/main.java/com/hanulso/controller/MapController.java
src/main.java/com/hanulso/mapper/FavoriteMapper.java
src/main.java/com/hanulso/mapper/FavoriteMapper.xml
src/main.java/com/hanulso/service/FavoriteService.java
src/main.java/com/hanulso/service/FavoriteServiceImpl.java
src/main/webapp/WEB-INF/views/alert/alert_list.jsp
src/main/webapp/WEB-INF/views/favorite/looked_room.jsp
src/main/webapp/WEB-INF/views/map/map_modal_view.jsp
src/main/webapp/resources/css/mystyle.css

FAVORITE COMPLETE

---

src/main/webapp/WEB-INF/views/alert/alert_list.jsp
src/main/webapp/WEB-INF/views/favorite/looked_room.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/user/user_login.jsp
src/main/webapp/resources/css/mystyle.css

User Login 디자인 및 Index 페이지 

---

src/main/webapp/WEB-INF/views/admin/manage/admin_cor_list.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/notice/notice_view.jsp
src/main/webapp/WEB-INF/views/tip/tip_view.jsp

중개사 이미지 동그랗게

---

src/main.java/com/hanulso/controller/AlertController.java
src/main.java/com/hanulso/domain/PremiumVO.java
src/main.java/com/hanulso/mapper/PremiumMapper.java
src/main.java/com/hanulso/mapper/PremiumMapper.xml
src/main.java/com/hanulso/service/PremiumService.java
src/main.java/com/hanulso/service/PremiumServiceImpl.java
src/main/webapp/WEB-INF/views/alert/alert_list.jsp

결제 시스템 추가 ( 진행중 )

---

src/main.java/com/hanulso/controller/UserController.java
src/main.java/com/hanulso/mapper/TipMapper.xml
src/main.java/com/hanulso/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/map/map_view.jsp
src/main/webapp/WEB-INF/views/tip/tip_list.jsp
src/main/webapp/WEB-INF/views/user/user_delete_check.jsp
src/main/webapp/resources/css/navbar.css
src/main/webapp/resources/css/translate.css

ADMIN 제외 디자인 완료

---

src/main/webapp/resources/css/navbar.css
src/main/webapp/resources/css/translate.css

css 간단 수정 ( 헤더 색상 변경 )

---

src/main/webapp/WEB-INF/views/alert/alert_list.jsp
src/main/webapp/WEB-INF/views/favorite/looked_room_non.jsp
src/main/webapp/WEB-INF/views/include/footer.jsp
src/main/webapp/WEB-INF/views/index.jsp

알림 페이지 CSS 수정

---

src/main.java/com/hanulso/controller/KakaoController.java
src/main.java/com/hanulso/mapper/UserMapper.xml
src/main/webapp/WEB-INF/views/alert/alert_list.jsp

카카오 로그인 기능 및 Alert List 수정

---

src/main/webapp/WEB-INF/views/coroperation/cor_view.jsp

Cor_view CSS 수정
